server:
  context-path: /
  port: 10002

logging:
  level:
    root: INFO

spring:
  cache:
    type: CAFFEINE
    cache-names:
      - siteCache
      - clientGoodpayCache
    caffeine:
      spec: maximumSize=10000, expireAfterWrite=360m
  schedule:
    zkConnectString: 127.0.0.1:2181
    rootPath: /zto-schedule/sync
    zkSessionTimeout: 60000
    userName: admin
    password: admin
    isCheckParentPath: true


Mybatis:
  Database[0]:
    datasource: usercenter
    sqlSessionFactory: usercenterFactory
    TransactionManager: usercenterTransaction
    driverClassName: oracle.jdbc.driver.OracleDriver
    jdbcUrl:
    username:
    password:
    connectionTestQuery: SELECT 'Hello World' FROM DUAL
    connectionTimeout: 30000
    validationTimeout: 30000
    idleTimeout: 30000
    maxLifetime: 180000
    maximumPoolSize: 5
    minimumIdle: 1
    mapper:  ${package}.mapper.usercenter
    ##注意替换
    mapperLocations: classpath*:com/zto/consumer4scan/mapper/usercenter/*.xml
    typeAliasesPackage:  ${package}.domain.usercenter
  Database[1]:
    datasource: ztm
    sqlSessionFactory: ztmFactory
    TransactionManager: ztmTransaction
    driverClassName: oracle.jdbc.driver.OracleDriver
    jdbcUrl:
    username:
    password:
    connectionTestQuery: SELECT 'Hello World' FROM DUAL
    connectionTimeout: 30000
    validationTimeout: 30000
    idleTimeout: 30000
    maxLifetime: 180000
    maximumPoolSize: 5
    minimumIdle: 1
    mapper:  ${package}.mapper.ztm
    mapperLocations: classpath*:com/zto/consumer4scan/mapper/ztm/*.xml
    typeAliasesPackage:  ${package}.domain.ztm